version: '3.9'
services:
  postgres:
    build:
      context: ./conf
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
    container_name: postgres_api_todo_challenge
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 30s
        timeout: 10s
        retries: 5
    networks:
      - api-todo-challenge
  # api-service:
  #   build: .
  #   volumes:
  #     - .:/home/node/app
  #   container_name: todo-challenge
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - api-todo-challenge
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   links:
  #     - postgres
networks:
    api-todo-challenge:
        driver: bridge
